export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_LOGOUT = 'SIGNUP_LOGOUT';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const GET_POSTS = 'GET_POSTS';
export const LOADER_START = 'LOADER_START';
export const RESPONSE_FAIL = 'RESPONSE_FAIL';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';